# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request_target:
  push:
  branches:
            -master
            -Devolper
  jobs:
   test:
   name: running a unit Test
    runs-on:ubuntu-latest
    
     steps
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name:  install
      run: |npm install
        
  - name:  Test 
    run: npm Test 

